### ISSUE TITLE
Premenovanie repozitaru

### ISSUE THREAD

**Issue by fr6nco** [aks-2017/semestralne-zadania-semestralne-zadanie-xcelesova-xvalkoj1#1]
Ahojte,

zle som sa vyjadril v maili. Proism poslite mi vase x[meno] loginy ja updatenem meno timu a repozitaru. Budete musiet asi updatenut origin vo vasich gitoch.

Tomas

**Comment by BarboraCelesova** [comment]
Ahoj,

73692 je xcelesova
74338 je xvalkoj1



B.

Dňa 23. októbra 2017, 10:50, Thomas Boros <notifications@github.com>
napísal(-a):
